# Generated by Django 2.0.6 on 2018-06-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=6)),
                ('valor_contribuicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_contribuicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_atualizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('U', 'Regime prórpio - União'), ('E', 'Regime prórpio - Estado'), ('M', 'Regime prórpio - Município'), ('G', 'Regime geral - INSS')], default='U', max_length=1)),
                ('decimo_terceiro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuinte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('data_nascimento', models.DateTimeField()),
                ('data_ingresso_servico_publico', models.DateTimeField()),
                ('data_simulacao', models.DateTimeField(blank=True, null=True)),
                ('beneficio_regra_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficio_media_todas_contribuicoes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficio_inss', models.DecimalField(decimal_places=2, default=5645.8, max_digits=10)),
                ('beneficio_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ipca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(db_index=True, max_length=6)),
                ('indice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acumulado', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='contribuinte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.Contribuinte'),
        ),
    ]
